#!/bin/sh

mkdir -p /tmp/notif
name=$1
shift

if test -e /tmp/notif/$name
then
    replace=$(cat /tmp/notif/$name)

    if [[ $replace -eq $replace ]]
    then
        replace="-r $replace"
    else
        replace=
    fi
fi

dunstify -p $replace "$@" > /tmp/notif/$name
